# 56 cards minor arcanas 
There are 56 cards in the minor arcana divided into four suits: Wands, Cups, Swords and Pentacles.
Each of these suits stands for a particular approach to life.

The minor arcana brings those themes down into the practical arena to show how they operate in daily events.
It represent the concerns, activities and emotions that make up the dramas of our everyday lives.

* Themes
** Wands
The Wands are the suit of creativity, action and movement.
They are associated with such qualities as enthusiasm, adventure, risk-taking and confidence.
This suit corresponds to the yang, or masculine principle, in Chinese philosophy and is associated with the element Fire.
A flickering flame is the perfect symbol of the Wands force.
This energy flows outward and generates passionate involvement.


** Cups
The Cups are the suit of emotions and spiritual experience.
They describe inner states, feelings and relationship patterns.
The energy of this suit flows inward.
Cups correspond to the yin, or feminine principle, in Chinese philosophy and are associated with the element Water.
The ability of water to flow and fill up spaces, to sustain and to reflect changing moods makes it the ideal symbol of the Cups suit.


** Swords
The Swords are the suit of intellect, thought and reason.
They are concerned with justice, truth and ethical principles.
Swords are associated with the element Air.
A cloudless sky, open and light-filled, is a symbol of the mental clarity that is the Swords ideal.
This suit is also associated with states that lead to disharmony and unhappiness.
Our intellect is a valuable asset, but as an agent of ego, it can lead us astray if it is not infused with the wisdom of our Inner Guide.


** Pentacles
The Pentacles are the suit of practicality, security and material concerns.
They are associated with the element Earth and the concrete requirements of working with matter.
In Pentacles, we celebrate the beauty of nature, our interactions with plants and animals and our physical experiences in the body.
Pentacles also represent prosperity and wealth of all kinds.
Sometimes this suit is called the Coins, an obvious symbol of the exchange of goods and services in the physical world.


* Number Cards
** Tens
A Ten takes the themes introduced by an Ace to their logical conclusion.
If you take the love, intimacy and emotions of the Ace of Cups to their ultimate, you have the joy, peace and family love of the Ten of Cups.

** Middle Cards
Each of the middle, numbered cards presents a different aspect of a suit.
The Wands explore such themes as personal power (card 2), leadership (card 3), excitement (card 4) and competition (card 5).
A card may approach an idea from several angles.
The Five of Pentacles shows the many faces of want - hard times (material want), ill health (physical want), and rejection (emotional want.

** Aces
An Ace announces the themes of its suit.
The Ace of Cups stands for love, emotions, intuition, and intimacy - ideas that are explored in the other cards of the Cups suit.
An Ace always represents positive forces.
It is the standard-bearer for the best its suit has to offer.


* Court Cards
The court cards are people with personalities that reflect the qualities of their suit and rank.
The court cards show us certain ways of being in the world so that we can use those styles when appropriate.

** King 
A King is mature and masculine.
He is a doer whose focus is outward on the events of life.
He demonstrates authority, control and mastery in some area associated with his suit.
A King's style is strong, assertive and direct.
He is concerned with results and practical, how-to matters.

** Queen  
A Queen is mature and feminine.
She embodies the qualities of her suit, rather than acting them out.
Her focus is inward, and her style, relaxed and natural.
A Queen is less concerned with results than with the enjoyment of just being in the world.
She is associated with feelings, relationships and self-expression.

** Knight
A Knight is an immature teenager.
He cannot express himself with balance.
He swings wildly from one extreme to another as he tries to relate successfully to his world.
A Knight is prone to excess, but he is also eager and sincere, and these qualities redeem him in our eyes.
We admire his spirit and energy.

** Page 
A Page is a playful child.
He acts out the qualities of his suit with pleasure and abandon.
His approach may not be deep, but it is easy, loose and spontaneous.
He is a symbol of adventure and possibility.

